---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBu1gYtk5EtFdwRKClpT5PLONHJADP/os37Xgo8WmKZD+F38u/eOblRzMQwMSFc4lSXyna6Rd3DSuh1Y7Z3iD3LdFj7Q0NhBZX/0OWUGCs1mWrfNoqO70Te9HdrAeniy9vUb7xq26ZC78nzsq7KW+08RZvklmNvVHHBL0TFguG0oPzlPPJEkiD9z9waon1TKxASmROPHL+uKwIkPPneq0SiQNGkmSmwHnxXB2kN4VjGdVpWo7r6A1XqAw1KLleMygzfeJkKVKvG5u4c/1WfBpTFeW/4KxJZ/YH+Jh1TC6DRq+Ikusqep+mUWKI6IUCZURjMR9QOyLXjxbkQp986RNoHlYxjnY3D6n7ad/a6/H/OISwX9k4Ed6k+Uc7T1NSZ+TYZ5gvYYvsHCpy5yg6AMQ1j4/O811pp5OkumB/u/Xv6jhSDq+YQgwZca2jdoTPkKxLeV8vXMf492nvVrHxkVNHdYJGDF1ddr9qmRv1IcgHwKXp2AQRH89CiOPgjobxBmJHLcoNUtzuVTEhdAPu3uNpZ5Nm8bYE5Discnve6vs/gzrd5VHfZsMut8hRHeLjxxs7MXnYWezqKCtBJIyC7aNql6veKcQs3LJ3b1XCM1m9ruM1776fzo8yVE3Dj9n99ZYCwlY86iPEn0cgVZxJY67TEf/0yv5MCJo2XPxAl4eGfS1uKvtMoIDJSyHzDs+1nWt0SEh+N75HijEPqCIzDotzuw42u8dqF+cI+vJz/LGxfeH68oRXStxZQ+7X6dXF85OjJI47A52xwyC6Fz+8sLYzU0jtbfkD21CIn5M1GLgmqn7wF8q6ngZunSogoYEJhb9APtO1PdOrQLfS1JYlXJQyZyNNKut9f0/OV1ZdZSk3Nhaly1ewTzT89udoaUlU6YdXxJ1vPoK7VafI4pVQPovCzpm18xk6tH9VWlx07jfyzZAcbU5PZtGK0
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
    type: Opaque
