apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler/
      chart: descheduler
      targetRevision: 0.35.1
      helm:
        releaseName: descheduler
        valueFiles:
          - $values/argocd/apps/descheduler/values.yaml
    - repoURL: https://github.com/Atanu484/atanus-homelab.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
