---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/renovatebot/helm-charts.git
      path: charts/renovate
      targetRevision: renovate-46.44.0
      helm:
        releaseName: renovate
        valueFiles:
          - $values/argocd/apps/renovate/values.yaml
    - repoURL: https://github.com/Atanu484/atanus-homelab.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
