minecraftServer:
  eula: "TRUE"
  version: "LATEST"
  type: VANILLA
  difficulty: easy
  gameMode: survival
  motd: "Atanu's Homelab - Welcome!"
  maxPlayers: 10
  onlineMode: false
  pvp: false
  viewDistance: 10
  spawnProtection: 0
  serviceType: NodePort
  nodePort: 30565

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 2000m

persistence:
  storageClass: longhorn
  dataDir:
    enabled: true
    Size: 10Gi

dnsConfig:
  options:
    - name: ndots
      value: "1"
