apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://opensearch-project.github.io/helm-charts
      chart: opensearch
      targetRevision: 3.5.0
      helm:
        releaseName: opensearch
        valueFiles:
          - $values/argocd/apps/opensearch/values.yaml
    - repoURL: https://github.com/Atanu484/atanus-homelab.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
