apiVersion: v1
kind: Secret
metadata:
  name: db-encryption
  namespace: homarr
type: Opaque
stringData:
  # Must be 64-char hex (e.g. openssl rand -hex 32). Change breaks existing encrypted DB.
  db-encryption-key: "4d3b0a81aa5df20b67924fadaf6759a62143f561c058a050b2f03c40b07234da"
