service:
  main:
    type: NodePort
    ports:
      http:
        port: 3000
        nodePort: 31000

persistence:
  config:
    enabled: true
    type: pvc
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000
