ingress:
  enabled: false

service:
  ui:
    type: NodePort
    nodePort: 30808

preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  automaticEngineUpgrade: true
  concurrentAutomaticEngineUpgradePerNodeLimit: 1

extraObjects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: longhorn-system
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/audit: privileged

  - apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
    metadata:
      name: longhorn-critical
    value: 1000000000
    globalDefault: false
    description: "Priority class for Longhorn components."
