apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 8.0.1
      helm:
        releaseName: falco
        valueFiles:
          - $values/argocd/apps/falco/values.yaml
    - repoURL: https://github.com/Atanu484/atanus-homelab.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
