apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archiveteam-warrior
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      releaseName: archiveteam-warrior
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: archiveteam/warrior
                  tag: latest
                env:
                  DOWNLOADER: "protostar"
                  SELECTED_PROJECT: "auto"

        service:
          main:
            controller: main
            type: NodePort
            ports:
              http:
                port: 8001
                nodePort: 31071

        persistence:
          data:
            enabled: true
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 5Gi
            storageClassName: longhorn
            globalMounts:
              - path: /home/warrior

  destination:
    server: https://kubernetes.default.svc
    namespace: archiveteam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true