apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://runatlantis.github.io/helm-charts
    chart: atlantis
    targetRevision: 5.27.0
    helm:
      releaseName: atlantis
      values: |
        orgAllowlist: "github.com/Atanu484/atanus-homelab"

        vcsSecretName: atlantis-vcs

        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
