apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commafeed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts/
    chart: app-template
    targetRevision: 3.7.3
    helm:
      releaseName: commafeed
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: athou/commafeed
                  tag: latest-h2
                ports:
                  - name: http
                    containerPort: 8082

        service:
          main:
            controller: main
            type: NodePort
            ports:
              http:
                port: 8082
                nodePort: 31140

        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 2Gi
            globalMounts:
              - path: /commafeed/data

  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true