apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 8.0.1
    helm:
      releaseName: falco
      values: |
        # Recommended these days: eBPF driver (no kernel module build pain)
        driver:
          kind: ebpf
        
        # Explicitly tells Falco to run the eBPF setup in privileged mode
        ebpf:
          privileged: true

        falcosidekick:
          enabled: true
          webui:
            enabled: true
            user: "admin:CHANGE-ME-STRONG-PASSWORD"
            service:
              type: NodePort
              nodePort: 31020
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # Instructs ArgoCD to label the namespace on creation to bypass PSA baseline
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged