apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: 2.1.0
    helm:
      releaseName: homepage
      values: |
        service:
          main:
            type: NodePort
            ports:
              http:
                port: 3000
                nodePort: 31000

        persistence:
          config:
            enabled: true
            type: pvc
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 2Gi

        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: home.atanuslab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
