apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloakx
    targetRevision: "7.1.9"
    helm:
      releaseName: keycloak
      values: |
        replicas: 1

        image:
          repository: quay.io/keycloak/keycloak
          tag: "26.5.5"
          pullPolicy: IfNotPresent

        command:
          - "/opt/keycloak/bin/kc.sh"
          - "start"
          - "--http-port=8080"
          - "--hostname-strict=false"

        extraEnv: |
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "CHANGE-ME-STRONG-PASSWORD"
          - name: JAVA_OPTS_APPEND
            value: >-
              -Djgroups.dns.query=keycloak-headless

        service:
          type: NodePort
          httpNodePort: 30990

        proxy:
          enabled: true
          mode: forwarded
          http:
            enabled: true

        database:
          vendor: postgres
          hostname: keycloak-db-postgresql
          port: "5432"
          database: keycloak
          username: keycloak
          password: "CHANGE-ME-DB-PASSWORD"

        dbchecker:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: iam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
