apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Atanu484/atanus-homelab
    targetRevision: master
    path: apps-config/longhorn-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
