apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io
    chart: minio
    targetRevision: 5.4.0
    helm:
      releaseName: minio
      values: |
        mode: standalone
        replicas: 1

        persistence:
          enabled: true
          size: 5Gi
          accessMode: ReadWriteOnce
          storageClass: longhorn

        service:
          type: NodePort
          nodePort: 30950

        consoleService:
          type: NodePort
          nodePort: 30951

  destination:
    server: https://kubernetes.default.svc
    namespace: storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true