apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.35.0
    helm:
      releaseName: pihole
      values: |
        replicaCount: 1

        adminPassword: "CHANGE-ME-STRONG-PASSWORD"

        DNS1: "1.1.1.1"
        DNS2: "1.0.0.1"

        serviceWeb:
          type: NodePort
          nodePort: 31053

        serviceDns:
          type: NodePort

        persistentVolumeClaim:
          enabled: true
          storageClass: longhorn
          size: 2Gi

        extraVolumes:
          - name: dnsmasq
            persistentVolumeClaim:
              claimName: pihole-dnsmasq
        extraVolumeMounts:
          - name: dnsmasq
            mountPath: /etc/dnsmasq.d

        extraObjects:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: pihole-dnsmasq
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: longhorn
              resources:
                requests:
                  storage: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
