---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBICOXpK9ibvCsN1YADqBroYrvG545Uo7Nk6pd19OUY4VVuJQUuikg1zXFQESoCeol3HYRaxaN0ez5vrZJL2CJevt7Una/7nmf18PDqD36N2RKYMwUjijL5AEYP4oihavjqdFRL0kKzCRIr4kzFaBgSzHaf2iogi9Cz3X336ngFt2Txy1EvH8JHWvFUt4lRUTfz7ipQeHC+w8EYUUbx14rUE+qWG0GIY+ER1B5rByTWybCTeSurQW3VQf0sgvEz0z6JTGkNUWCqlbXFAfsDEX0g50vvPCFKUS1BLfMjAOfcFEw5wyl7gr3uBbZ2WiAvKCHEoAclhoHtNlgenNhjvPYqoW1zuwiqoiWEQN3xuLFXUwsz6t/fjJibLRmTxSKeLVSqexWaHUbiX1uDFA/K9X1VBLvcbwbkvM1ut2PQeNLuY8LSodTszM11cxs+A3ycnHiOUWi1y3xPt4Mz94BPpKPFVf7wfs+2tG0zgf/ikm630bltjNhZMwlzCvkvX3rzjCaaQUj/K/NcKEvqoBtoL6PhUHK+2Xedi4+rKWQ4G/bP5CnKDdskfiuOs3BuiQD5ec4Dg6tJxrlRSoNvkLZ4O21AR+xDnLQDyrsipD/Y7oarPBPLqzR9dSdTe6ofhG7KnnukVEfDtRtLk21MCtySWJVVcwBLD5sCGubu7IAGQ4NeDt7fCH8NSDmYAdBORjQVyLHCkVvBqhcTsSTifMSAzfWKWYT/QNYTe3YjFfyIUJX5OH+YmnAc00hnYOAHRYBA+wm1w2BlNbHJC6ZGuQMUiyH41sh2oX/mObvtW068fZw3fjeHYsmh3Tobf2+Tj44=
  template:
    metadata:
      name: renovate-secrets
      namespace: renovate
