---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: renovate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCyFTCE7ZPzL2muCTI+2j0nuhgK51xnPl3zsvxmgJogv9wUMuWcL7XVQXWXKuprHjp6dHZOvQ3uqzgP/O6MPeAsB+6Wo/8mvLOSS4EMAMCNl9iek82ZF14EPTBFa2axx+WbLVUCJBASi6MqosAg3n4ABnPD49i8HQap/Bk/SqwRxfUCfjcs/BvUV838I9kW0mIZqyzCk4Eob0EKIoCCAmGDit6kuwRExYTMyHczZdnaQdhCb1w/TNtacnaERSlGetu5hRYLt1w9XgdmPNIdZItfNeoemxJpTHREQhd6N8w3msPD5y/cAbEG5xBH/eujhIzbjA9ZEBlVl5wF++dne9eVVxcuvAnHw9C1DtAYm7gzP+YAWvrY3KSWY6kwoJXADxoUViXqHjWvpwwC6Zk6sOGlPzef2bqVLVQK3dvIHunXQIcqVUni6BMpAXVOvm9IMs8R3YiMeXEQUrn4C64W3whJzQ41C/XdHN5/K9y1U99zrEUaJBFS8/Jguy2x2Cbftwm9QuTWeyX3A3PhxzUUaJen8mFBCaQNCcWLxFdUSfri8VoNZ0cLgQs2Ks11OhBAbYYBXkZDzNz3Lg00ELyGgF9BO3w0S12NS2TB6vtQJO34Ka0hw3WBmMH3O2/NMQaLIlXeqFtmMj9YDkpdPD+RpiZtlnQh4HJbTEU2LYR86JpzxKYZrqlvxVgPvwkp4QJcOVN9ps6CHBaiRKCvKrs1dxygsS/7UOBx3rBMDNixxDKWgFj9/ZiAmC0HeZvqho7dVcMnoTBD6Jp3Wz6p1l3wvEziR5fSJv1cdhZ3VMpqJhGddmPimP5JPdR9Vzprc2k=
  template:
    metadata:
      name: renovate-secrets
      namespace: renovate
