apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 39.0.5
    helm:
      releaseName: traefik
      values: |
        service:
          type: NodePort
          spec:
            externalTrafficPolicy: Cluster

        ports:
          web:
            port: 8000
            expose:
              default: true
            exposedPort: 80
            protocol: TCP
            nodePort: 31180

          websecure:
            port: 8443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP
            nodePort: 31443

          traefik:
            port: 9000
            expose:
              default: true
            exposedPort: 9000
            protocol: TCP
            nodePort: 31901

        api:
          dashboard: true
          insecure: true

        additionalArguments:
          - "--providers.kubernetescrd=true"
          - "--providers.kubernetesingress=true"
          - "--providers.kubernetesCRD.allowCrossNamespace=true"

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-basicauth
  namespace: traefik
spec:
  encryptedData:
    users: AgB12yV+YcSeeNZ/+ajmvslDKEHUf9FZf6csVa9v5L5fSi+GI7k+17RYE1+UUXpx7gC8EJ/iD4HhOWKp8uOlI5isHx9IiX4H0PPJmRtO7Y4muo0aJfOoWcz3LRZGbM7Yk4cH4QlH7QZ5A0CVSH9MWZnBG8WV/CpbjRxrXrkw4Ig5dhsF/aztIlMHE+Eal5y8vRS9TipmpGCGI/J0z8QPoi78m7v7oY55Yda79RkycrG78fGR6FFj0t2yyI+HgSsw0KYS4A9V8bmDfgDP2lelExpHeql1Ff0NBgrC174IHLxktFIbQ0p43azRKDHo1k0tgkzrMiX8VPK2PeXCwQKAVrMB9Fte6vj0tus2GXVASPRfhd2HXmOwnpnH+7uzPLRHeidIBrunUBHsixw3PYZQHrWbIOzmsrwLzhGOH/dANQI9pluhL9+U+1QBXSx2F1Xt0Hg4CsX61wF1MTw6XmTQRGebLntZbLg/gdArws7QlP7xh6SE/L7GtDa6vmSQJeDZcH+ErtwfzdHHg5S/Ues7CYkUwwJ87vgkwt2WWRMLR0ai51a9KW2oWxWfw/J+G+XQd1cfaeo+jIdb2+G1ugSK9mMXVrXV5COAKUnCZIrfSUU2x/O63aochyaXh2lYjJ9BZeL56ByFW0Q+K2zAX1MDgsE3rekjVjm8ns4phxLhe/0aIrt0OCwUn6lTnKQi/8Li6/1gzh46bnouAJ57xRu92rzuo9oSSPcbnGTs70vfR6WaTU/R4TPL9fCM+DbUkb1mYJgbf/2kvhsKutRXGN0Cxde2jgrekQ==
  template:
    metadata:
      name: traefik-basicauth
      namespace: traefik
    type: Opaque

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basicauth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-basicauth
