apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 26.1.0
    helm:
      releaseName: traefik
      values: |
        service:
          type: NodePort
          spec:
            externalTrafficPolicy: Local

        ports:
          web:
            port: 8000
            expose: true
            exposedPort: 80
            protocol: TCP
            nodePort: 30080

          websecure:
            port: 8443
            expose: true
            exposedPort: 443
            protocol: TCP
            nodePort: 30443

          traefik:
            port: 9000
            expose: true
            exposedPort: 9000
            protocol: TCP
            nodePort: 30901
        api:
          dashboard: true
          ingressRoute:
            dashboard:
              enabled: true
              # This exposes dashboard on the "traefik" entryPoint (port 9000 -> NodePort 30901)
              entryPoints: ["traefik"]
              # default matchRule is fine, but explicit is clearer
              matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)

        additionalArguments:
          - "--providers.kubernetescrd=true"
          - "--providers.kubernetesingress=true"

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true