apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: 0.34.6
    helm:
      releaseName: vaultwarden
      values: |
        image:
          repository: vaultwarden/server
          tag: latest

        service:
          type: ClusterIP

        storage:
          enabled: true
          size: 2Gi
          class: longhorn
          dataDir: /data

        extraObjects:
          - apiVersion: v1
            kind: Service
            metadata:
              name: vaultwarden-nodeport
              labels:
                app.kubernetes.io/name: vaultwarden
                app.kubernetes.io/instance: vaultwarden
                app.kubernetes.io/component: vaultwarden
            spec:
              type: NodePort
              selector:
                app.kubernetes.io/name: vaultwarden
                app.kubernetes.io/instance: vaultwarden
                app.kubernetes.io/component: vaultwarden
              ports:
                - name: http
                  port: 80
                  targetPort: 8080
                  nodePort: 32080
                  protocol: TCP
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true