apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vesta
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      releaseName: vesta
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: niiknow/vestacp
                  tag: latest
                ports:
                  - name: http
                    containerPort: 80

        service:
          main:
            controller: main
            type: NodePort
            ports:
              http:
                port: 80
                nodePort: 31170

        persistence:
          data:
            type: persistentVolumeClaim
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 2Gi
            globalMounts:
              - path: /data
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true