apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-single
    targetRevision: 0.12.11
    helm:
      releaseName: victoria-metrics
      values: |
        server:
          persistentVolume:
            enabled: true
            storageClass: longhorn
            accessModes:
              - ReadWriteOnce
            size: 50Gi
          service:
            type: NodePort
            servicePort: 8428
            nodePort: 31230 # Access the Victoria Metrics vmui/API here
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true