apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      releaseName: wakapi
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: ghcr.io/muety/wakapi
                  tag: latest
                ports:
                  - name: http
                    containerPort: 3000

        service:
          main:
            type: NodePort
            ports:
              http:
                port: 3000
                nodePort: 31190 # Access Wakapi GUI here

        persistence:
          data:
            enabled: true
            type: pvc
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 5Gi
            mountPath: /data
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true