apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/tracking-id: root-app:argoproj.io/Application:argocd/gitea
spec:
  project: default
  sources:
    - repoURL: https://dl.gitea.com/charts/
      chart: gitea
      targetRevision: 12.5.0
      helm:
        releaseName: gitea
        valueFiles:
          - $values/argocd/apps/gitea/values.yaml
    - repoURL: https://github.com/Atanu484/atanus-homelab.git
      targetRevision: master
      ref: values
      path: argocd/apps/gitea
      directory:
        exclude: '{application.yaml,values.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
