apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: 2.7.0
    helm:
      releaseName: jellyfin
      values: |
        image:
          repository: lscr.io/linuxserver/jellyfin
          tag: latest
          pullPolicy: IfNotPresent

        service:
          type: NodePort
          port: 8096
          nodePort: 31050

        podSecurityContext:
          fsGroup: 1000
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000

        jellyfin:
          env:
            - name: TZ
              value: "Europe/Tallinn"
            # linuxserver-style IDs (optional but usually recommended)
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

        persistence:
          config:
            enabled: true
            size: 1Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce
          media:
            enabled: true
            type: pvc
            size: 3Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true