apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karakeep
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://karakeep-app.github.io/helm-charts/
      chart: karakeep
      targetRevision: 0.31.0
      helm:
        releaseName: karakeep
        valueFiles:
          - $values/argocd/apps/karakeep/values.yaml
    - repoURL: https://github.com/Atanu484/atanus-homelab.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
