apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanboard
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.6.2
      helm:
        releaseName: kanboard
        values: |
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: kanboard/kanboard
                    tag: latest
                  ports:
                    - name: http
                      containerPort: 80

          service:
            main:
              controller: main
              type: NodePort
              ports:
                http:
                  port: 80
                  nodePort: 31250

          persistence:
            data:
              type: persistentVolumeClaim
              storageClass: longhorn
              accessMode: ReadWriteOnce
              size: 5Gi
              globalMounts:
                - path: /var/www/app/data
    - repoURL: https://github.com/Atanu484/atanus-homelab.git
      targetRevision: master
      path: argocd/apps/kanboard
      directory:
        exclude: 'application.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
