apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniserve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      releaseName: miniserve
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: svenstaro/miniserve
                  tag: latest
                args: ["/data"]
                ports:
                  - name: http
                    containerPort: 8080

        service:
          main:
            type: NodePort
            ports:
              http:
                port: 8080
                nodePort: 31150

        persistence:
          data:
            enabled: true
            type: pvc
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 20Gi
            mountPath: /data
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
