apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    helm:
      releaseName: searxng
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: searxng/searxng
                  tag: latest
                ports:
                  - name: http
                    containerPort: 8080

        service:
          main:
            type: NodePort
            ports:
              http:
                port: 8080
                nodePort: 31160

        persistence:
          config:
            enabled: true
            type: pvc
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 1Gi
            mountPath: /etc/searxng
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
